version: '3.9'

services:
  db-academit:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Adrian12234..'
      MYSQL_PASSWORD: 'Adrian12234..'
      MYSQL_DATABASE: 'academit-db'
      MYSQL_USER: 'fran'
    expose:
      - 3310
    ports:
      - "3310:3306"
    volumes:
      - ./data:/var/lib/mysql